# Generated by Django 4.0.6 on 2022-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=120)),
                ('idi', models.CharField(default='', max_length=120)),
                ('tittle', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('category', models.CharField(max_length=120)),
            ],
        ),
    ]
