# Generated by Django 4.0.6 on 2022-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashbord_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(default='', max_length=120)),
                ('tittle', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('dashboardid', models.TextField()),
                ('embade_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='data_cubix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(default='', max_length=120)),
                ('class_color', models.CharField(default='', max_length=120)),
                ('tittle', models.CharField(default='', max_length=120)),
                ('calc_col', models.CharField(default='', max_length=120)),
                ('class_name', models.CharField(default='', max_length=120)),
                ('special', models.BooleanField(default=False)),
                ('data_position', models.FloatField(default=0)),
                ('enable_data', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='inputs_fileds',
            fields=[
                ('idi', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('colname', models.CharField(default='', max_length=120)),
                ('display_name', models.CharField(default='', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nav_uppers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(default='', max_length=120)),
                ('link_to', models.CharField(default='', max_length=360)),
                ('position_place', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='side_cubix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(default='', max_length=120)),
                ('tittle', models.CharField(max_length=120)),
                ('inputs', models.IntegerField()),
                ('check_type', models.CharField(default='regular', max_length=120, null=True)),
                ('disable', models.BooleanField(default=False)),
                ('hidden_class', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
