# Generated by Django 4.0.6 on 2022-07-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dashbord_in_data_cubix_inputs_fileds_nav_uppers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idi', models.CharField(default='', max_length=120)),
                ('typei', models.CharField(default='', max_length=120)),
                ('category', models.CharField(default='', max_length=120)),
                ('tittle', models.CharField(default='', max_length=120)),
                ('qty', models.FloatField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dashbord_in',
        ),
        migrations.DeleteModel(
            name='data_cubix',
        ),
        migrations.DeleteModel(
            name='inputs_fileds',
        ),
        migrations.DeleteModel(
            name='nav_uppers',
        ),
        migrations.DeleteModel(
            name='side_cubix',
        ),
    ]
