# Generated by Django 4.0.6 on 2022-07-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_products_delete_dashbord_in_delete_data_cubix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='idi',
        ),
    ]
